name: Chart Release

on:
  push:
    branches:
      - main

env:
  CHART_REPOSITORY: https://huseyinbabal.github.io/helm-charts
  GIT_USER: github-actions[bot]
  GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout to gh-pages for Helm
        uses: actions/checkout@v4
        with:
          path: .
          ref: gh-pages

      - name: Set git 'user.name' and 'user.email'
        run: |
          git config --global user.name "${{ env.GIT_USER }}"
          git config --global user.email ${{ env.GIT_EMAIL }}

      - name: Publish Chart
        run: |
          helm package -d ${{ github.workspace }} ./kusadasi --version 0.0.0-${{ github.sha }}
          helm repo index --url "${{ env.CHART_REPOSITORY }}" --merge ./index.yaml .
          git add .
          git commit -m "${{ github.sha }} Botkube Helm chart release"
          git push

